import type { Metadata } from 'next';
import Gilroy from 'next/font/local';
import './globals.css';
import './fonts.css';
import { cn } from '@/lib/utils';

const gilroy = Gilroy({
	src: [{ path: '../assets/font/gilroy/Gilroy-Regular.otf' }],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={gilroy.className}>{children}</body>
		</html>
	);
}
